server:
  port: 8084
  servlet:
    context-path: /api
    session:
      cookie:
        domain: localhost

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/company
    username: root
    password: yunmo_Hua0209

knife4j:
  enable: true



